sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zw20001009
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: web-zhuwei
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxde83a1da1ff80a4a
    secret: d7dc5bfecae9eb28e0378d67bd4ea7db